GET http://localhost:5001/todos 

###
POST http://localhost:5001/todos
Content-Type: application/json

{
    "Id" : 1,
    "Name" : "hellothere",
    "DueDate" : "2023-12-31",
    "IsCompleted" : false
}

### 
GET http://localhost:5001/todos/2

###
DELETE http://localhost:5001/todos/2
###
GET http://localhost:5001/tasks/1